# Transcribe Demo

Start by loading nemo models. The first nemo model is for transcription and the second for restoring punctuation and capitalization

In [ ]:
import nemo.collections.asr as nemo_asr
import nemo.collections.nlp as nemo_nlp
nemo_asr.models.EncDecRNNTBPEModel.list_available_models()
asr_model = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained("nvidia/stt_en_conformer_transducer_xlarge")
punc_model = nemo_nlp.models.PunctuationCapitalizationModel.from_pretrained(model_name="punctuation_en_bert")

In [3]:
text = asr_model.transcribe(['wavs/2086-149220-0033.wav'])
print(text[0])
punc_text = punc_model.add_punctuation_capitalization(text[0])
print(punc_text[0])

Transcribing:   0%|          | 0/1 [00:00<?, ?it/s]

["well i don't wish to see it any more observed phoebe turning away her eyes it is certainly very like the old portrait"]
[NeMo I 2022-12-24 08:54:20 punctuation_capitalization_model:1153] Using batch size 1 for inference
[NeMo I 2022-12-24 08:54:20 punctuation_capitalization_infer_dataset:123] Max length: 27
[NeMo I 2022-12-24 08:54:20 data_preprocessing:404] Some stats of the lengths of the sequences:
[NeMo I 2022-12-24 08:54:20 data_preprocessing:406] Min: 25 |                  Max: 25 |                  Mean: 25.0 |                  Median: 25.0
[NeMo I 2022-12-24 08:54:20 data_preprocessing:412] 75 percentile: 25.00
[NeMo I 2022-12-24 08:54:20 data_preprocessing:413] 99 percentile: 25.00


100%|██████████| 1/1 [00:00<00:00, 18.04batch/s]

inp_ids:
 tensor([[  101,  2092,  1045,  2123,  1005,  1056,  4299,  2000,  2156,  2009,
          2151,  2062,  5159, 18188,  3810,  2185,  2014,  2159,  2009,  2003,
          5121,  2200,  2066,  1996,  2214,  6533,   102]]) inp_type_ids:
 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]]) inp_mask:
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.]])
punct_logits:
 tensor([[[ 4.8503, -2.9812, -0.4151, -2.8845],
         [ 0.1323,  3.0063, -1.4942, -2.4208],
         [ 6.8541, -2.1068, -2.5900, -2.8318],
         [ 6.9369, -1.6710, -2.7945, -2.7861],
         [ 0.7901, -0.5896,  0.4698, -0.4055],
         [ 6.9584, -1.7214, -2.7256, -2.7364],
         [ 6.7784, -1.6331, -2.5843, -2.7147],
         [ 7.0229, -1.9993, -2.6366, -2.6633],
         [ 6.8360, -1.8749, -2.5989, -2.7527],
         [ 5.7690, -0.9293, -2.3619, -3.0327],
         [ 6.3577, -1.5796, -2.2

In [8]:
import nemo.collections.nlp as nemo_nlp
punc_model = nemo_nlp.models.PunctuationCapitalizationModel.from_pretrained(model_name="punctuation_en_bert")
punc_model.add_punctuation_capitalization(['he will sleep till noon but before it\'s dark he\'ll have every picnic basket that\'s in jellystone park'])

[NeMo I 2022-12-24 08:35:50 cloud:56] Found existing object /root/.cache/torch/NeMo/NeMo_1.13.0/punctuation_en_bert/93b0369b5e0d147f61895feffcbcfb88/punctuation_en_bert.nemo.
[NeMo I 2022-12-24 08:35:50 cloud:62] Re-using file from: /root/.cache/torch/NeMo/NeMo_1.13.0/punctuation_en_bert/93b0369b5e0d147f61895feffcbcfb88/punctuation_en_bert.nemo
[NeMo I 2022-12-24 08:35:50 common:911] Instantiating model from pre-trained checkpoint
[NeMo I 2022-12-24 08:35:52 tokenizer_utils:130] Getting HuggingFace AutoTokenizer with pretrained_model_name: bert-base-uncased, vocab_file: /tmp/tmpduuhpz_b/tokenizer.vocab_file, merges_files: None, special_tokens_dict: {}, and use_fast: False


Using eos_token, but it is not set yet.
Using bos_token, but it is not set yet.
[NeMo W 2022-12-24 08:35:54 modelPT:222] You tried to register an artifact under config key=tokenizer.vocab_file but an artifact for it has already been registered.
[NeMo W 2022-12-24 08:35:54 modelPT:142] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    use_audio: false
    audio_file: null
    sample_rate: 16000
    use_bucketing: true
    batch_size: 32
    preload_audios: true
    use_tarred_dataset: false
    label_info_save_dir: null
    text_file: text_train.txt
    labels_file: labels_train.txt
    tokens_in_batch: null
    max_seq_length: 128
    num_samples: -1
    use_cache: true
    cache_dir: null
    get_label_frequences: false
    verbose: true
    n_jobs: 0
    tar_metadata_file: null
    tar_shuffle_n: 1
    shard_strategy: scatter
    shuffle: true

[NeMo I 2022-12-24 08:35:57 save_restore_connector:243] Model PunctuationCapitalizationModel was successfully restored from /root/.cache/torch/NeMo/NeMo_1.13.0/punctuation_en_bert/93b0369b5e0d147f61895feffcbcfb88/punctuation_en_bert.nemo.
[NeMo I 2022-12-24 08:35:57 punctuation_capitalization_model:1153] Using batch size 1 for inference
[NeMo I 2022-12-24 08:35:57 punctuation_capitalization_infer_dataset:123] Max length: 27
[NeMo I 2022-12-24 08:35:57 data_preprocessing:404] Some stats of the lengths of the sequences:
[NeMo I 2022-12-24 08:35:57 data_preprocessing:406] Min: 25 |                  Max: 25 |                  Mean: 25.0 |                  Median: 25.0
[NeMo I 2022-12-24 08:35:57 data_preprocessing:412] 75 percentile: 25.00
[NeMo I 2022-12-24 08:35:57 data_preprocessing:413] 99 percentile: 25.00


100%|██████████| 1/1 [00:00<00:00, 12.99batch/s]

inp_ids:
 tensor([[  101,  2002,  2097,  3637,  6229, 11501,  2021,  2077,  2009,  1005,
          1055,  2601,  2002,  1005,  2222,  2031,  2296, 12695, 10810,  2008,
          1005,  1055,  1999, 20919,  9221,  2380,   102]]) inp_type_ids:
 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]]) inp_mask:
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1.]])
punct_logits:
 tensor([[[ 6.0038, -2.5931, -0.5617, -3.7318],
         [ 6.8852, -2.2081, -2.7300, -2.6337],
         [ 6.7950, -1.3456, -2.9009, -2.6717],
         [ 6.5351, -0.9809, -2.9165, -2.8146],
         [ 7.0712, -1.2897, -3.0332, -2.8454],
         [ 2.0359,  3.7379, -1.7103, -4.1689],
         [ 5.6519,  0.2897, -2.8706, -3.8278],
         [ 6.7520, -1.1492, -2.9665, -2.8356],
         [ 7.0598, -1.7922, -2.9366, -2.6153],
         [ 7.0001, -1.7423, -2.8704, -2.5851],
         [ 7.0212, -1.7382, -2.9

["He will sleep till noon, but before it's dark, he'll have every picnic basket that's in Jellystone Park."]

In [4]:
import torch
torch.cuda.get_arch_list()
torch.cuda.get_device_properties(0)
torch.cuda.is_available()

True

In [6]:
text = "My name is Clara and I live in Berkeley California Ist das eine Frage Frau Müller"
result = model.restore_punctuation(text)
print(result)

My name is Clara and I live in Berkeley, California. Ist das eine Frage, Frau Müller?


In [ ]:
print(result)